
<header>
	<h1>
		<span class="glyphicon glyphicon-file" aria-hidden="true"></span>
		Páginas
	</h1>
</header>


<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Páginas</h3>
			</div>
			<div class="panel-body">
				<?= Html::linkTo("Crear Página", "admin/create",  "class=\"btn btn-success\"")?>
                <table class="table table-bordered table-stripped mt-2">
					<thead>
						<tr>
							<th width="50%">Título</th>
							<th width="20%">Categoría</th>
							<th width="10%">Estado</th>
							<th>Opciones</th>
						</tr>
					</thead>
					<tbody>
                	<?php foreach($list_of_items as $item):?>
                	<tr>
							<td width="50%"><?= $item['titulo']?></td>
							<td width="20%"><?= Categoria::getNombre($item['categoria_id'])?></td>
							<td width="10%" align="center"><?= $item['activo'] == "1" ? "Activa" : "Inactiva"?></td>
							<td align="center">
                            <?= Html::linkTo("<i class='glyphicon glyphicon-pencil'></i>", "admin/edit/" . $item['id'], 
                            "class=\"btn btn-info btn-sm\" title=\"Editar Página\"")?>
                            <?php if(intval($item['activo']) == 1): ?>
								<?= Html::linkTo("<i class='glyphicon glyphicon-minus-sign'></i>", "admin/cambiar_estado/" . $item['id'], 
                            		"class=\"btn btn-danger btn-sm\" title=\"Inactivar página\"")?>
							<?php else: ?>
							<?= Html::linkTo("<i class='glyphicon glyphicon-plus-sign'></i>", "admin/cambiar_estado/" . $item['id'], 
                            "class=\"btn btn-success btn-sm\" title=\"Activar página\"")?>
							<?php endif ?>
                		</td>
						</tr>
                	<?php endforeach;?>
                    </tbody>
				</table>
			</div>
		</div>
	</div>
</div>