<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    
    <title>IsaliaPHP - Administrador</title>

    <!-- Bootstrap core CSS -->
    <link href="<?= PUBLIC_PATH ?>css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="<?= PUBLIC_PATH ?>css/navbar-fixed-top.css" rel="stylesheet">
    <link href="<?= PUBLIC_PATH ?>css/custom.css" rel="stylesheet">
    <link href="<?= PUBLIC_PATH ?>assets/summernote/summernote.min.css" rel="stylesheet">
    
    
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">IsaliaPHP</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li id="portada"><a href="<?= PUBLIC_PATH?>">
            	<span class="glyphicon glyphicon-home" aria-hidden="true"></span> Home
            	</a></li>
        	<li><?= Html::linkTo('<span class="glyphicon glyphicon-file"></span> Páginas', "admin")?></li>
        	<li><?= Html::linkTo('<span class="glyphicon glyphicon-folder-close"></span> Categorías', "categorias")?></li>
        	
            
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="<?= PUBLIC_PATH?>usuarios/perfil" title="Ver mi perfil"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> <?=Session::get("user_name")?></a></li>
            <li><a href="<?= PUBLIC_PATH?>login/signout"> <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> Salir</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
      <?php echo Load::getContent(); ?>
        	
	  <?php echo Load::partial('footer'); ?>


    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="<?= PUBLIC_PATH ?>js/jquery.min.js"></script>
    <script src="<?= PUBLIC_PATH ?>js/bootstrap.min.js"></script>
    
    <script src="<?= PUBLIC_PATH ?>assets/summernote/summernote.min.js"></script>
	  <script src="<?= PUBLIC_PATH ?>assets/summernote/lang/summernote-es-ES.min.js"></script>
        
    <script>
    	if (typeof window['initialize'] === 'function'){
    		window['initialize']()
    	}
    </script>
  </body>
</html>
