<header>
    <h1>
        <span class="glyphicon glyphicon-folder-close" aria-hidden="true"></span>
        Crear Categoría
    </h1>
</header>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Información de la Categoría</h3>
            </div>
            <div class="panel-body">

            <?= Html::formOpen("categorias/edit/" . $current_item['id'],"class=\"form-horizontal mt-2\"") ?>
                    <div class="form-group">
                        <label for="data_nombre" class="col-sm-2 control-label">Nombre</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" 
                            	id="data_nombre" name="data[nombre]"
                            	value="<?= $current_item['nombre']?>">
                        </div>
                    </div>
                    <div class="form-group text-right pr-2">
                    <?= Html::linkTo("Cancelar", "categorias", 
                            "class=\"btn btn-default\"")?>
                        <button type="submit" class="btn btn-success">Actualizar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>