
<header>
	<h1>
		<span class="glyphicon glyphicon-folder-close" aria-hidden="true"></span>
		Categorías
	</h1>
</header>


<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Categorías</h3>
			</div>
			<div class="panel-body">
				<?= Html::linkTo("Crear Categoría", "categorias/create",  "class=\"btn btn-success\"")?>
                <table class="table table-bordered table-stripped mt-2">
					<thead>
						<tr>
							<th width="70%">Nombre</th>
							<th width="10%">Estado</th>
							<th>Opciones</th>
						</tr>
					</thead>
					<tbody>
                	<?php foreach($list_of_items as $item):?>
                	<tr>
							<td width="70%"><?= $item['nombre']?></td>
							<td width="10%" align="center"><?= $item['activa'] == "1" ? "Activa" : "Inactiva"?></td>
							<td align="center">
                            <?= Html::linkTo("<i class='glyphicon glyphicon-pencil'></i>", "categorias/edit/" . $item['id'], 
                            "class=\"btn btn-info btn-sm\" title=\"Editar Categoría\"")?>
                            <?php if(intval($item['activa']) == 1): ?>
								<?= Html::linkTo("<i class='glyphicon glyphicon-minus-sign'></i>", "categorias/cambiar_estado/" . $item['id'], 
                            		"class=\"btn btn-danger btn-sm\" title=\"Inactivar categoría\"")?>
							<?php else: ?>
							<?= Html::linkTo("<i class='glyphicon glyphicon-plus-sign'></i>", "categorias/cambiar_estado/" . $item['id'], 
                            "class=\"btn btn-success btn-sm\" title=\"Activar categoría\"")?>
							<?php endif ?>
                		</td>
						</tr>
                	<?php endforeach;?>
                    </tbody>
				</table>
			</div>
		</div>
	</div>
</div>