<div class="panel panel-primary mt-2">
	<div class="panel-heading">
		<h3 class="panel-title">IsaliaPHP rc1</h3>
	</div>
	<div class="panel-body">
		<a href="https://github.com/IsaliaPHP/IsaliaPHP/archive/refs/tags/rc1.zip" target="_blank">
		<i class="fa fa-file-zip-o"></i> Descargar (zip)</a>
		<br>
		<a href="https://github.com/IsaliaPHP/IsaliaPHP/archive/refs/tags/rc1.tar.gz" target="_blank">
		<i class="fa fa-file-zip-o"></i> Descargar (tar.gz)</a>
		<br><br>		
		<a title="Calidad de Código" href="https://scrutinizer-ci.com/g/IsaliaPHP/IsaliaPHP/"><img src="https://scrutinizer-ci.com/g/IsaliaPHP/IsaliaPHP/badges/quality-score.png?b=main"></a>
		<br>
		<a title="Pasa la compilación" href="https://scrutinizer-ci.com/g/IsaliaPHP/IsaliaPHP/"><img src="https://scrutinizer-ci.com/g/IsaliaPHP/IsaliaPHP/badges/build.png?b=main"></a>
		<br>
		<a title="Nivel de Mantenibilidad" href="https://codeclimate.com/github/IsaliaPHP/IsaliaPHP/maintainability"><img src="https://api.codeclimate.com/v1/badges/2d2532a4912884b87b8b/maintainability" /></a>
	</div>
</div>

<div class="panel panel-primary mt-2">
	<div class="panel-heading">
		<h3 class="panel-title">Enlaces</h3>
	</div>
	<div class="panel-body">
		<a href="https://github.com/IsaliaPHP/IsaliaPHP/wiki" target="_blank">
		<i class="fa fa-book"></i> Documentación en la Wiki</a>
		<br>
		<a href="https://github.com/IsaliaPHP/IsaliaPHP" target="_blank">
		<i class="fa fa-github"></i> Repositorio Github</a>
		<br>
		<a href="https://www.youtube.com/channel/UCypDZMq3skWAJRrY3W1SFVg" target="_blank">
		<i class="fa fa-youtube"></i> Canal de Youtube</a>
		<br>
		<a href="https://groups.google.com/g/isaliaphp-framework" target="_blank">
		<i class="fa fa-google"></i> Grupo de Google</a>
		
		
	</div>
</div>